let profile=null,rows={experience:[],education:[],certificates:[],skills:[],projects:[]};const $=id=>document.getElementById(id);
async function init(){const {data:{session}}=await supabaseClient.auth.getSession();session?showDashboard():showLogin()}
function showLogin(){$("loginBox").classList.remove("hidden");$("dashboard").classList.add("hidden")}
function showDashboard(){$("loginBox").classList.add("hidden");$("dashboard").classList.remove("hidden");loadData()}
$("loginBtn").onclick=async()=>{const {error}=await supabaseClient.auth.signInWithPassword({email:$("email").value,password:$("password").value});if(error)$("loginMsg").textContent=error.message;else showDashboard()}
$("logoutBtn").onclick=async()=>{await supabaseClient.auth.signOut();showLogin()}
async function loadData(){
 const {data:p}=await supabaseClient.from("profiles").select("*").limit(1).maybeSingle();profile=p||{};
 ["name","role","profileEmail","phone","location","cvUrl","headline","bio","years","projectsCount","certificatesCount","commitment"].forEach(k=>{const map={profileEmail:"email",cvUrl:"cv_url",projectsCount:"projects_count",certificatesCount:"certificates_count"};$(k).value=profile[map[k]||k]||""});
 if(profile.photo_url){$("photoPreview").src=profile.photo_url;$("photoPreview").style.display="block"}
 for(const key of Object.keys(rows)){const table=key==="experience"?"experiences":key;const {data}=await supabaseClient.from(table).select("*").order("sort_order");rows[key]=data||[]}renderAll()
}
function renderAll(){renderExperience();renderEducation();renderCertificates();renderSkills();renderProjects()}
function editorButton(){return `<button class="btn danger" type="button" onclick="this.closest('.editor-item').remove()">حذف</button>`}
function renderExperience(){$("experienceEditor").innerHTML=rows.experience.map(x=>`<div class="editor-item"><div class="grid two"><label>الفترة<input data-k="period" value="${a(x.period)}"></label><label>المسمى<input data-k="title" value="${a(x.title)}"></label><label>الجهة<input data-k="org" value="${a(x.org)}"></label></div><label>الوصف<textarea data-k="description">${a(x.description)}</textarea></label>${editorButton()}</div>`).join("")}
function renderEducation(){$("educationEditor").innerHTML=rows.education.map(x=>`<div class="editor-item"><div class="grid two"><label>الفترة<input data-k="period" value="${a(x.period)}"></label><label>المؤهل<input data-k="title" value="${a(x.title)}"></label><label>الجهة<input data-k="org" value="${a(x.org)}"></label></div><label>الوصف<textarea data-k="description">${a(x.description)}</textarea></label>${editorButton()}</div>`).join("")}
function renderCertificates(){$("certificateEditor").innerHTML=rows.certificates.map(x=>`<div class="editor-item"><label>اسم الشهادة<input data-k="title" value="${a(x.title)}"></label><label>الملف<input type="file" accept="image/*,.pdf" onchange="uploadCertificate(this)"></label><input type="hidden" data-k="file_url" value="${a(x.file_url||"")}"><div class="hint">${x.file_url?"تم رفع ملف":"لم يتم رفع ملف"}</div>${editorButton()}</div>`).join("")}
function renderSkills(){$("skillsEditor").innerHTML=rows.skills.map(x=>`<div class="editor-item"><label>الفئة<input data-k="category" value="${a(x.category)}"></label><label>المهارات (كل مهارة في سطر)<textarea data-k="items">${a((x.items||[]).join("\n"))}</textarea></label>${editorButton()}</div>`).join("")}
function renderProjects(){$("projectsEditor").innerHTML=rows.projects.map(x=>`<div class="editor-item"><label>اسم المشروع<input data-k="title" value="${a(x.title)}"></label><label>الوصف<textarea data-k="description">${a(x.description)}</textarea></label>${editorButton()}</div>`).join("")}
function collect(container,keys){return [...$(container).children].map(el=>{const o={};keys.forEach(k=>o[k]=el.querySelector(`[data-k="${k}"]`)?.value||"");return o})}
function addExperience(){rows.experience.push({period:"",title:"",org:"",description:""});renderExperience()}function addEducation(){rows.education.push({period:"",title:"",org:"",description:""});renderEducation()}function addCertificate(){rows.certificates.push({title:"",file_url:""});renderCertificates()}function addSkill(){rows.skills.push({category:"",items:[]});renderSkills()}function addProject(){rows.projects.push({title:"",description:""});renderProjects()}
async function uploadFile(file,path){const {error}=await supabaseClient.storage.from(STORAGE_BUCKET).upload(path,file,{upsert:true});if(error)throw error;return supabaseClient.storage.from(STORAGE_BUCKET).getPublicUrl(path).data.publicUrl}
window.uploadCertificate=async input=>{try{const f=input.files[0];if(!f)return;const url=await uploadFile(f,`certificates/${crypto.randomUUID()}-${f.name}`);input.closest(".editor-item").querySelector('[data-k="file_url"]').value=url;input.nextElementSibling.textContent="تم رفع الملف بنجاح"}catch(e){alert(e.message)}}
$("photoFile").onchange=async e=>{try{const f=e.target.files[0];if(!f)return;profile.photo_url=await uploadFile(f,`profile/${crypto.randomUUID()}-${f.name}`);$("photoPreview").src=profile.photo_url;$("photoPreview").style.display="block"}catch(e){alert(e.message)}}
$("saveBtn").onclick=async()=>{try{
 const payload={id:profile.id,name:$("name").value,role:$("role").value,email:$("profileEmail").value,phone:$("phone").value,location:$("location").value,cv_url:$("cvUrl").value,headline:$("headline").value,bio:$("bio").value,years:$("years").value,projects_count:$("projectsCount").value,certificates_count:$("certificatesCount").value,commitment:$("commitment").value,photo_url:profile.photo_url||null};let r=await supabaseClient.from("profiles").upsert(payload);if(r.error)throw r.error;
 const sets=[["experiences","experience",["period","title","org","description"]],["education","education",["period","title","org","description"]],["certificates","certificates",["title","file_url"]],["skills","skills",["category","items"]],["projects","projects",["title","description"]]];
 for(const [table,key,keys] of sets){let d=await supabaseClient.from(table).delete().neq("id","00000000-0000-0000-0000-000000000000");if(d.error)throw d.error;let arr=collect(key+"Editor",keys).map((x,i)=>({...x,sort_order:i}));if(key==="skills")arr.forEach(x=>x.items=x.items.split("\n").map(s=>s.trim()).filter(Boolean));if(arr.length){let q=await supabaseClient.from(table).insert(arr);if(q.error)throw q.error}}
 $("saveMsg").textContent="تم حفظ جميع البيانات بنجاح";setTimeout(()=>$("saveMsg").textContent="",3000);await loadData()
}catch(e){alert("حدث خطأ: "+e.message)}}
function a(s=""){return String(s).replace(/&/g,"&amp;").replace(/"/g,"&quot;").replace(/</g,"&lt;").replace(/>/g,"&gt;")}init();
